FROM openjdk:8-jdk-alpine
#ARG JAR_FILE=target/*.jar

# Required for starting application up.
RUN apk update && apk add /bin/sh

RUN mkdir -p /opt/app
ENV PROJECT_HOME /opt/app

ARG JAR_FILE=build/libs/*.jar


COPY ${JAR_FILE} $PROJECT_HOME/app.jar

WORKDIR $PROJECT_HOME

ENTRYPOINT ["java","-jar","./app.jar"]

EXPOSE 8081
